### ISSUE TITLE
Self hosted version

### ISSUE THREAD

**Issue by tgkenney** [Beatusvir/phasmophobia-assistant#1]
First, I just want to say this is a pretty cool project.  Makes playing the game much more enjoyable when you don't have to flip through the journal to narrow things down.

Second, I'm sure I'm not alone in this when I say I'd like to be able to self-host this on my own equipment.  I'm not a fan of services like Heroku and Netlify.  They have their places, but I'd hate to lose access to this program when the free tiers run out again.

I threw together a quick dockerfile that lets me build this project and host it via docker on my own server.  I'd be more than happy to create a pull request to merge that in if you'd think other people would use it.  Just a suggestion, so if you don't agree feel free to close this issue.

Thanks!

**Comment by Beatusvir** [comment]
hey @tgkenney thats why its on github, please feel free to create a PR, new branch would be great. I'll review it and merge it later today

**Comment by tgkenney** [comment]
Sure thing, I just created it.  I was only able to point the PR at master, but if you want me it merged into a different branch feel free to create one and I can point the PR at that

**Comment by Beatusvir** [comment]
@tgkenney Added the branch

**Comment by tgkenney** [comment]
Edited

**Comment by Beatusvir** [comment]
Merged
